# Generated by Django 6.0.4 on 2026-05-12 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi'], 'Faqat mp4 va avi formatlarga ruhsat')]),
        ),
    ]
